version: "3.8"

services:
  node_inoa:
    container_name: node_inoa
    build:
      dockerfile: ./DockerFile
      context: .
      target: base
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    env_file: .env
    command: npm run dev

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
